/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as SyllabusRouteImport } from './routes/syllabus'
import { Route as ExperimentsIndexRouteImport } from './routes/experiments/index'
import { Route as ExperimentsExperimentIdRouteImport } from './routes/experiments/$experimentId'
import { Route as LearnIndexRouteImport } from './routes/learn/index'
import { Route as LearnLessonIdRouteImport } from './routes/learn/$lessonId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const SyllabusRoute = SyllabusRouteImport.update({
  id: '/syllabus',
  path: '/syllabus',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperimentsIndexRoute = ExperimentsIndexRouteImport.update({
  id: '/experiments/',
  path: '/experiments/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperimentsExperimentIdRoute = ExperimentsExperimentIdRouteImport.update({
  id: '/experiments/$experimentId',
  path: '/experiments/$experimentId',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/learn/',
  path: '/learn/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnLessonIdRoute = LearnLessonIdRouteImport.update({
  id: '/learn/$lessonId',
  path: '/learn/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/playground': typeof PlaygroundRoute
  '/practice': typeof PracticeRoute
  '/progress': typeof ProgressRoute
  '/studio': typeof StudioRoute
  '/syllabus': typeof SyllabusRoute
  '/experiments/$experimentId': typeof ExperimentsExperimentIdRoute
  '/learn/$lessonId': typeof LearnLessonIdRoute
  '/experiments/': typeof ExperimentsIndexRoute
  '/learn/': typeof LearnIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/playground': typeof PlaygroundRoute
  '/practice': typeof PracticeRoute
  '/progress': typeof ProgressRoute
  '/studio': typeof StudioRoute
  '/syllabus': typeof SyllabusRoute
  '/experiments/$experimentId': typeof ExperimentsExperimentIdRoute
  '/learn/$lessonId': typeof LearnLessonIdRoute
  '/experiments': typeof ExperimentsIndexRoute
  '/learn': typeof LearnIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/playground': typeof PlaygroundRoute
  '/practice': typeof PracticeRoute
  '/progress': typeof ProgressRoute
  '/studio': typeof StudioRoute
  '/syllabus': typeof SyllabusRoute
  '/experiments/$experimentId': typeof ExperimentsExperimentIdRoute
  '/learn/$lessonId': typeof LearnLessonIdRoute
  '/experiments/': typeof ExperimentsIndexRoute
  '/learn/': typeof LearnIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/playground'
    | '/practice'
    | '/progress'
    | '/studio'
    | '/syllabus'
    | '/experiments/$experimentId'
    | '/learn/$lessonId'
    | '/experiments/'
    | '/learn/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/playground'
    | '/practice'
    | '/progress'
    | '/studio'
    | '/syllabus'
    | '/experiments/$experimentId'
    | '/learn/$lessonId'
    | '/experiments'
    | '/learn'
  id:
    | '__root__'
    | '/'
    | '/playground'
    | '/practice'
    | '/progress'
    | '/studio'
    | '/syllabus'
    | '/experiments/$experimentId'
    | '/learn/$lessonId'
    | '/experiments/'
    | '/learn/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlaygroundRoute: typeof PlaygroundRoute
  PracticeRoute: typeof PracticeRoute
  ProgressRoute: typeof ProgressRoute
  StudioRoute: typeof StudioRoute
  SyllabusRoute: typeof SyllabusRoute
  ExperimentsExperimentIdRoute: typeof ExperimentsExperimentIdRoute
  LearnLessonIdRoute: typeof LearnLessonIdRoute
  ExperimentsIndexRoute: typeof ExperimentsIndexRoute
  LearnIndexRoute: typeof LearnIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/syllabus': {
      id: '/syllabus'
      path: '/syllabus'
      fullPath: '/syllabus'
      preLoaderRoute: typeof SyllabusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiments/': {
      id: '/experiments/'
      path: '/experiments'
      fullPath: '/experiments/'
      preLoaderRoute: typeof ExperimentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiments/$experimentId': {
      id: '/experiments/$experimentId'
      path: '/experiments/$experimentId'
      fullPath: '/experiments/$experimentId'
      preLoaderRoute: typeof ExperimentsExperimentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/': {
      id: '/learn/'
      path: '/learn'
      fullPath: '/learn/'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$lessonId': {
      id: '/learn/$lessonId'
      path: '/learn/$lessonId'
      fullPath: '/learn/$lessonId'
      preLoaderRoute: typeof LearnLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlaygroundRoute: PlaygroundRoute,
  PracticeRoute: PracticeRoute,
  ProgressRoute: ProgressRoute,
  StudioRoute: StudioRoute,
  SyllabusRoute: SyllabusRoute,
  ExperimentsExperimentIdRoute: ExperimentsExperimentIdRoute,
  LearnLessonIdRoute: LearnLessonIdRoute,
  ExperimentsIndexRoute: ExperimentsIndexRoute,
  LearnIndexRoute: LearnIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
